import { AppShell } from "@/components/shell/AppShell";
import { albums, artists, songs } from "@/lib/music/catalog";
import { Card } from "@/components/ui/Card";

export default function ArtistDashboardPage() {
  const artist = artists[0] ?? null;
  const artistSongs = songs.filter((song) => song.artistId === artist?.id);
  const artistAlbums = albums.filter((album) => album.artistId === artist?.id);
  return <AppShell><div className="mx-auto max-w-7xl py-14"><p className="text-pulse">Artist Login Active</p><h1 className="text-5xl font-black">Artist Dashboard</h1><div className="mt-8 grid gap-4 md:grid-cols-4"><Card><strong>Streams</strong><p className="mt-2 text-3xl font-black">1.4M</p></Card><Card><strong>Listeners</strong><p className="mt-2 text-3xl font-black">842K</p></Card><Card><strong>Saves</strong><p className="mt-2 text-3xl font-black">11.8K</p></Card><Card><strong>Completion</strong><p className="mt-2 text-3xl font-black">84%</p></Card></div><section className="mt-10 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-2xl font-black">Upload Songs</h2><input className="mt-4 w-full rounded-2xl bg-white/10 p-3" placeholder="Song title" /><input className="mt-3 w-full rounded-2xl bg-white/10 p-3" placeholder="Audio file URL or uploaded key" /><button className="mt-4 rounded-full bg-white px-5 py-3 font-bold text-ink">Save song</button></Card><Card><h2 className="text-2xl font-black">Upload Albums</h2><input className="mt-4 w-full rounded-2xl bg-white/10 p-3" placeholder="Album title" /><input className="mt-3 w-full rounded-2xl bg-white/10 p-3" placeholder="Cover image URL or uploaded key" /><button className="mt-4 rounded-full bg-white px-5 py-3 font-bold text-ink">Save album</button></Card></section><section className="mt-10 grid gap-6 lg:grid-cols-2"><Card><h2 className="text-2xl font-black">Edit Music</h2>{artistSongs.map((song) => <div key={song.id} className="mt-3 rounded-2xl bg-white/10 p-3"><strong>{song.title}</strong><p className="text-sm text-slate-400">{song.plays.toLocaleString()} plays</p></div>)}</Card><Card><h2 className="text-2xl font-black">Artist Profile</h2><p className="mt-3 text-slate-300">{artist?.name} · {artist?.genre}</p><p className="mt-4 text-sm text-slate-400">Albums: {artistAlbums.map((album) => album.title).join(", ")}</p></Card></section></div></AppShell>;
}
